spring:
  datasource:
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
    username: {USERNAME}
    password: {PASSWORD}
  thymeleaf:
    mode: 'LEGACYHTML5'
  social:
    twitter:
      app-id: {TWITTER_APP_ID}
      app-secret: {TWITTER_APP_SECRET}
mybatis:
  mapper-locations: classpath:db/repository/*.xml
  configuration:
    map-underscore-to-camel-case: true